/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const VehicleType = IDL.Variant({
  'motorcycle' : IDL.Null,
  'scooter' : IDL.Null,
});
export const Capacity = IDL.Variant({
  'upTo200cc' : IDL.Null,
  'above200cc' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'repair' : IDL.Null,
  'fullService' : IDL.Null,
  'cleaning' : IDL.Null,
});
export const CleaningSubOption = IDL.Variant({
  'normalFoamWashing' : IDL.Nat,
  'colourFoamWashing' : IDL.Nat,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : Status,
  'vehicleType' : VehicleType,
  'serviceType' : ServiceType,
  'address' : IDL.Text,
  'mechanicName' : IDL.Opt(IDL.Text),
  'repairDetails' : IDL.Opt(IDL.Text),
  'cleaningSubOption' : IDL.Opt(CleaningSubOption),
  'capacity' : Capacity,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'assignMechanic' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        VehicleType,
        Capacity,
        ServiceType,
        IDL.Opt(IDL.Text),
        IDL.Opt(CleaningSubOption),
      ],
      [],
      [],
    ),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'updateBookingStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const VehicleType = IDL.Variant({
    'motorcycle' : IDL.Null,
    'scooter' : IDL.Null,
  });
  const Capacity = IDL.Variant({
    'upTo200cc' : IDL.Null,
    'above200cc' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'repair' : IDL.Null,
    'fullService' : IDL.Null,
    'cleaning' : IDL.Null,
  });
  const CleaningSubOption = IDL.Variant({
    'normalFoamWashing' : IDL.Nat,
    'colourFoamWashing' : IDL.Nat,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : Status,
    'vehicleType' : VehicleType,
    'serviceType' : ServiceType,
    'address' : IDL.Text,
    'mechanicName' : IDL.Opt(IDL.Text),
    'repairDetails' : IDL.Opt(IDL.Text),
    'cleaningSubOption' : IDL.Opt(CleaningSubOption),
    'capacity' : Capacity,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'assignMechanic' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          VehicleType,
          Capacity,
          ServiceType,
          IDL.Opt(IDL.Text),
          IDL.Opt(CleaningSubOption),
        ],
        [],
        [],
      ),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'updateBookingStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };