/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'customerName' : string,
  'status' : Status,
  'vehicleType' : VehicleType,
  'serviceType' : ServiceType,
  'address' : string,
  'mechanicName' : [] | [string],
  'repairDetails' : [] | [string],
  'cleaningSubOption' : [] | [CleaningSubOption],
  'capacity' : Capacity,
  'phoneNumber' : string,
}
export type Capacity = { 'upTo200cc' : null } |
  { 'above200cc' : null };
export type CleaningSubOption = { 'normalFoamWashing' : bigint } |
  { 'colourFoamWashing' : bigint };
export type ServiceType = { 'repair' : null } |
  { 'fullService' : null } |
  { 'cleaning' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type VehicleType = { 'motorcycle' : null } |
  { 'scooter' : null } |
  { 'electric' : null };
export interface _SERVICE {
  'assignMechanic' : ActorMethod<[string, string], undefined>,
  'createBooking' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      VehicleType,
      Capacity,
      ServiceType,
      [] | [string],
      [] | [CleaningSubOption],
    ],
    undefined
  >,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'updateBookingStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];